### ISSUE TITLE
how does the command `download-package` help?

### ISSUE THREAD

**Issue by Guangyi-Z** [huntzhan/pyenv-mirror#2]
Since all Pythons for Pyenv mirror is under dir `source`, what it the point to download Pythons into `$PYENV_ROOT/.../python-build/`?

**Comment by huntzhan** [comment]
Actually you have to download all the packages manually at the first time.

**Comment by Guangyi-Z** [comment]
If I am doing it right, would it make more sense to do: 

```
pyenv-mirror download-package 2.7.13 'path_to_source'
```

**Comment by huntzhan** [comment]
Oh, I see.
`download-package` needs information to find the URLs of related packages in order to download them. `<python-build-path>` is an optional argument to specify the path containing a bunch of files that mapping package name to related URLs for downloading.

`download-package` always download files to **current working directory**.

**Comment by Guangyi-Z** [comment]
I understand.
And I prefer to call those files as "index".

```
cd path_to_source
pyenv-mirror download-package 2.7.13 <python-build-path>
```

**Comment by huntzhan** [comment]
Yes you can.
:)
